In [1]:
import numpy as np

In [2]:
np_array = np.array([0,1,2,3])

In [3]:
np_array

array([0, 1, 2, 3])

In [5]:
np_array.dtype

dtype('int32')

In [7]:
str_array = np_array.astype(str)

In [8]:
str_array

array(['0', '1', '2', '3'], dtype='<U11')

In [10]:
for i in np_array:
    print (i*4)

0
4
8
12


In [11]:
for i in str_array:
    print (i*4)

0000
1111
2222
3333


In [12]:
din2_Array = np.array([[0,1,2,3],[2,4,5,6], [1,4,5,6]])

In [13]:
din2_Array.ndim # dimension of the array

2

In [14]:
din2_Array.shape

(3, 4)

In [15]:
din2_Array.size # no. of elements in array

12

In [16]:
np.mean(din2_Array) #overall

3.25

In [17]:
np.mean(din2_Array, axis = 0) # average per column

array([1., 3., 4., 5.])

In [18]:
din2_Array[0]

array([0, 1, 2, 3])

In [19]:
din2_Array

array([[0, 1, 2, 3],
       [2, 4, 5, 6],
       [1, 4, 5, 6]])

In [21]:
din2_Array[:2, :] #slicing [rows, columns]

array([[0, 1, 2, 3],
       [2, 4, 5, 6]])

In [22]:
din2_Array[:2, :2]

array([[0, 1],
       [2, 4]])

In [27]:
din2_Array[0][:: -1] #reversing the array row

array([3, 2, 1, 0])

In [28]:
?np.nan # to find documentation, an alternative to shift tab

In [30]:
arr = np.array([0,7,1,0,np.nan])

In [31]:
arr

array([ 0.,  7.,  1.,  0., nan])

In [34]:
np.mean(arr)

nan

In [35]:
arr2 = np.ma.masked_array(arr, np.isnan(arr))

In [36]:
np.mean(arr2)

2.0