In [11]:
# Exploring scipy library
from scipy import stats
import numpy as np

In [12]:
a = np.arange(0,20,1) #  creating a dataset

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
b = a.reshape(5,4) # creating an array 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
stats.sem(a)

1.3228756555322954

In [10]:
stats.sem(b)

array([2.82842712, 2.82842712, 2.82842712, 2.82842712])